### ISSUE TITLE
Minimum deployment target iOS 13

### ISSUE THREAD

**Issue by msoler95** [CodetrixStudio/CapacitorGoogleAuth#262]
I'm working with Capacitor 4.6.2 which requires iOS 13.  Xcode 14.2 and M1. When I compile the app I get the error:

    Compiling for iOS 12.0, but module 'Capacitor' has a minimum deployment target of iOS 13.0

If I change the minimum deployment target of this plugin to 13 (currently it shows as 12) the app compiles correctly.

In #247 they said it was solved, but it's still happening to me. Anyone else having this issue?

**Comment by yoojene** [comment]
I'm also getting this issue using Cap 4.6.2, XCode 14.2 but on an Intel Mac.  Using plugin version 3.2.1

<img width="1703" alt="Screenshot 2023-03-07 at 09 02 24" src="https://user-images.githubusercontent.com/14247260/223374930-75e536ea-6dc6-4b64-bfc7-4da4852c42b0.png">


@msoler95 where did you change the plugin deployment target? I can't get this to build , presumably since I upgraded XCode
